version: '3'

services:
  review-database:
    build: review-database/

  review-server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - 'review-database'
    volumes: 
      - './:/review-server'
    ports:
      - '3004:3004'
